
pipeline {
    
    agent any 
    
    tools {
      maven 'Mimaven Muy Guay pa compilar version 3.6'
    }

    stages {
        
        stage('1-Compilacíon/empaquetado básico'){
            steps {
                echo 'Lo que necesite hacer para compilar mi código'
                sh 'mvn compile'
            }
        }
        
        stage('2-Pruebas unitarias'){
            steps {
                echo 'Realizar pruebas unitarias'
                sh 'mvn test'
            }
            post{
                always {
                    echo 'Guardo el informe de pruebas unitarias'
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
        stage('3-Empaquetar la app para su posible ejecución'){
            steps {
                echo 'Empaqueto'
                sh 'mvn package'
            }
            post{
                success {
                    echo 'Guardo el empaquetado: war'
                    archiveArtifacts artifacts: 'target/*.war', followSymlinks: false
                }
            }
        }
        
    }

}
